apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-demo-quarkus
spec:
  selector:
    matchLabels:
      run: prometheus-demo-quarkus
  replicas: 2
  template:
    metadata:
      labels:
        run: prometheus-demo-quarkus
        app: prometheus-demo
    spec:
      containers:
        - name: prometheus-demo-quarkus
          image: wtfc63/prometheus-demo-quarkus:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /monitoring/health/liveness
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /monitoring/health/readiness
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5